name-template: 'Release $RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'BREAKING'
  minor:
    labels:
      - 'feature'
  default: patch
template: |
  ## What’s Changed

  $CHANGES
