dryRun: true
release:
  branches:
    - master
plugins:
  - '@semantic-release/commit-analyzer'
  - '@google/semantic-release-replace-plugin'
    replacements:
      - files: src/ya/experiment/__init__.py
        from: "__version__ = '.*'"
        to: "__version__ = '${nextRelease.version}'"
        results:
          - file: src/ya/experiment/__init__.py
            hasChanged: true
            numMatches: 1
            numReplacements: 1
         countMatches: true
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/git'
    assets:
      - src/ya/experiment/__init__.py

#
