name: Check Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'lint'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
