name: Check Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - uses: tonybajan/flake8-check-action@v1.0.0
      with:
        select: B,E,F,W
        repotoken: ${{ secrets.GITHUB_TOKEN }} 
