name: Draft a Release

on:
  push:
    branches:
      - master

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Create draft release'
        uses: release-drafter/release-drafter@v5
        id: draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Create version string'
        uses: booxmedialtd/ws-action-parse-semver@v1
        id: version
        with:
          input-string: ${{ steps.draft.outputs.tag_name }}
          version_extractor_regex: v(.*)$
      - name: Update __version__
        uses: jacobtomlinson/gha-find-replace@0.1.2
        with:
          find: __version__ = '.+'
          replace: __version__ = '${{ steps.version.outputs.fullversion }}'
          include: ".*\\.py"
#      - name: Update changelog
#        uses: thomaseizinger/keep-a-changelog-new-release@v1
#        with:
#          version: ${{ steps.version.outputs.replaced }}
      - name: Push __version__ and changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto commit: __version__"
          skip_dirty_check: true
#          tagging_message: ${{ steps.draft.outputs.tag_name }}
#          file_pattern: "*.py"
#          github_token: ${{ secrets.GITHUB_TOKEN }}

#      - name: Print draft release information
#        run: echo "id=${{ steps.draft.outputs.id }}, name=${{ steps.draft.outputs.name }}, tag_name=${{ steps.draft.outputs.tag_name }}"

#      - name: Bump versions
#        uses: remorses/bump-version@js
#        with:
#            version_file: ./src/ya/experiment/__init__.py
#            prefix: dir2 # this will prefix the created tag
#            github_token: ${{ secrets.GITHUB_TOKEN }}

#      - name: 'Set draft version number'
#        uses: pinio/draft-semver@v1
#        id: semver
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Print the next version
#        run: echo "Next version - ${{ steps.semver.outputs.version-identifier }}"
