name: Draft a Release

on:
#  pull_request:
#    types: closed
  push:
    branches:
      - master

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create draft release'
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Set draft version number'
        uses: pinio/draft-semver@v1
        id: semver
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print the next version
        run: echo "Next version - ${{ steps.semver.outputs.version-identifier }}"
